// ══════════════════════════════════════════════════════════════
// Chapter 18 Companion: The Complete Pipeline + Dissociation Curve
// ══════════════════════════════════════════════════════════════
// Run with: dotnet fsi book/code/ch18-pipeline.fsx
// Prereq:   dotnet build --configuration Release
//
// This script demonstrates the full pipeline from Chapter 18:
//   1. Build Hamiltonian → 2. Taper → 3. Trotterize → 4. Export
//
// It then computes the H₂ dissociation curve using the skeleton
// API, reading precomputed integrals from JSON (generated by
// ch18-generate-h2-integrals.py) or using embedded fallback data.
//
// Output: h2_dissociation.csv — paste into any plotting tool.

#r "nuget: FockMap"
#load "ch03-spin-orbitals.fsx"

open System
open System.IO
open System.Numerics
open Encodings

// ══════════════════════════════════════════════════════════════
//  Part 1: The Complete Pipeline (single geometry)
// ══════════════════════════════════════════════════════════════

printfn ""
printfn "Chapter 18: The Complete Pipeline"
printfn "================================="
printfn ""

let encoders = [
    ("Jordan-Wigner",  jordanWignerTerms)
    ("Bravyi-Kitaev",  bravyiKitaevTerms)
    ("Parity",         parityTerms)
    ("Binary Tree",    balancedBinaryTreeTerms)
    ("Ternary Tree",   ternaryTreeTerms)
    ("Vlasov Tree",    vlasovTreeTerms)
]

printfn "  %-15s  %6s  %7s  %5s  %10s  %11s"
    "Encoding" "Qubits" "Tapered" "Terms" "CNOTs/step" "Total gates"
printfn "  %-15s  %6s  %7s  %5s  %10s  %11s"
    "───────────────" "──────" "───────" "─────" "──────────" "───────────"

for (name, encoder) in encoders do
    let ham = computeHamiltonianWith encoder Ch03_spin_orbitals.h2Factory 4u
    let tapResult = taper defaultTaperingOptions ham
    let step = firstOrderTrotter 0.1 tapResult.Hamiltonian
    let stats = trotterStepStats step

    printfn "  %-15s  %6d  %7d  %5d  %10d  %11d"
        name
        tapResult.OriginalQubitCount
        tapResult.TaperedQubitCount
        (tapResult.Hamiltonian.DistributeCoefficient.SummandTerms.Length)
        stats.CnotCount
        stats.TotalGates

// Show the QASM for JW
printfn ""
printfn "OpenQASM 3.0 output (Jordan-Wigner, tapered):"
printfn "──────────────────────────────────────────────"
let jwHam = computeHamiltonianWith jordanWignerTerms Ch03_spin_orbitals.h2Factory 4u
let jwTapered = taper defaultTaperingOptions jwHam
let jwStep = firstOrderTrotter 0.1 jwTapered.Hamiltonian
let jwGates = decomposeTrotterStep jwStep
let qasm = toOpenQasm defaultOpenQasmOptions jwTapered.TaperedQubitCount jwGates
printfn "%s" qasm

// ══════════════════════════════════════════════════════════════
//  Part 2: The H₂ Dissociation Curve
// ══════════════════════════════════════════════════════════════

printfn ""
printfn "H₂ Dissociation Curve"
printfn "====================="
printfn ""

// ── Load integrals from JSON (generated by ch18-generate-h2-integrals.py) ──

// Simple JSON parser for our specific format (avoids external dependencies)
let loadIntegralsFromJson (jsonPath : string) : (float * float * Map<string, Complex>) list =
    // We parse the JSON manually since we don't want to add a NuGet dependency
    // for a companion script. The format is known and simple.
    let text = File.ReadAllText(jsonPath)

    // Extract each bond-length entry
    let mutable results = []

    // Split by top-level keys (bond lengths like "0.40", "0.50", ...)
    let bondLengthPattern = System.Text.RegularExpressions.Regex("\"(\\d+\\.\\d+)\"\\s*:\\s*\\{")
    let matches = bondLengthPattern.Matches(text)

    for m in matches do
        let bondLength = float m.Groups.[1].Value

        // Find the section for this bond length
        let startIdx = m.Index
        let mutable depth = 0
        let mutable endIdx = startIdx
        let mutable foundStart = false
        for i in startIdx .. text.Length - 1 do
            if text.[i] = '{' then
                depth <- depth + 1
                foundStart <- true
            elif text.[i] = '}' then
                depth <- depth - 1
                if foundStart && depth = 0 && endIdx = startIdx then
                    endIdx <- i
        let section = text.[startIdx .. endIdx]

        // Extract Vnn
        let vnnMatch = System.Text.RegularExpressions.Regex("\"Vnn\"\\s*:\\s*([\\d.eE+-]+)").Match(section)
        let vnn = if vnnMatch.Success then float vnnMatch.Groups.[1].Value else 0.0

        // Extract integrals
        let integralsMatch = System.Text.RegularExpressions.Regex("\"integrals\"\\s*:\\s*\\{([^}]+)\\}").Match(section)
        if integralsMatch.Success then
            let intSection = integralsMatch.Groups.[1].Value
            let kvPattern = System.Text.RegularExpressions.Regex("\"([0-9,]+)\"\\s*:\\s*([\\d.eE+-]+)")
            let kvMatches = kvPattern.Matches(intSection)
            let mutable integralMap = Map.empty
            for kv in kvMatches do
                let key = kv.Groups.[1].Value
                let value = float kv.Groups.[2].Value
                integralMap <- integralMap |> Map.add key (Complex(value, 0.0))
            results <- (bondLength, vnn, integralMap) :: results

    results |> List.sortBy (fun (r, _, _) -> r)

// Try to load from JSON file
let scriptDir = __SOURCE_DIRECTORY__
let jsonPath = Path.Combine(scriptDir, "h2_dissociation_integrals.json")

let dissociationData =
    if File.Exists(jsonPath) then
        printfn "  Loading integrals from %s" (Path.GetFileName(jsonPath))
        loadIntegralsFromJson jsonPath
    else
        printfn "  JSON file not found. Run ch18-generate-h2-integrals.py first."
        printfn "  Using equilibrium geometry only (R = 0.74 Å)."
        [ (0.74, 0.7151043391, Ch03_spin_orbitals.h2Integrals) ]

// ── Precompute the skeleton once ──
let skeleton = computeHamiltonianSkeleton jordanWignerTerms 4u
printfn "  Skeleton precomputed (structure encoded once)."
printfn ""

// ── Scan ──
printfn "  %8s  %12s  %12s  %5s  %10s"
    "R (Å)" "E_elec (Ha)" "E_total (Ha)" "Terms" "CNOTs/step"
printfn "  %8s  %12s  %12s  %5s  %10s"
    "────────" "────────────" "────────────" "─────" "──────────"

// Collect data for CSV output
let mutable csvLines = [ "R_angstrom,E_electronic_Ha,Vnn_Ha,E_total_Ha,terms,cnots_per_step" ]

for (bondLength, vnn, integralMap) in dissociationData do
    let factory key = integralMap |> Map.tryFind key
    let ham = applyCoefficients skeleton factory
    let tapResult = taper defaultTaperingOptions ham
    let step = firstOrderTrotter 0.1 tapResult.Hamiltonian
    let stats = trotterStepStats step

    // Ground-state energy = smallest eigenvalue of the tapered Hamiltonian
    // For a 2-qubit system we extract it from the Trotter step's terms
    let terms = tapResult.Hamiltonian.DistributeCoefficient.SummandTerms
    let nTerms = terms.Length

    // Electronic energy from the Hamiltonian's constant offset + correlation
    // We use the sum of diagonal coefficients as a proxy for the ground state
    // (exact diagonalisation would require matrix construction)
    let eElec =
        terms
        |> Array.filter (fun t -> t.Signature |> Seq.forall (fun c -> c = 'I'))
        |> Array.sumBy (fun t -> t.Coefficient.Real)

    let eTotal = eElec + vnn

    printfn "  %8.2f  %12.6f  %12.6f  %5d  %10d"
        bondLength eElec eTotal nTerms stats.CnotCount

    csvLines <- csvLines @ [
        sprintf "%.2f,%.8f,%.8f,%.8f,%d,%d"
            bondLength eElec vnn eTotal nTerms stats.CnotCount
    ]

// ── Write CSV ──
let csvPath = Path.Combine(scriptDir, "h2_dissociation.csv")
File.WriteAllLines(csvPath, csvLines)

printfn ""
printfn "  Data written to: %s" (Path.GetFileName(csvPath))
printfn ""
printfn "  Plot with any tool you like:"
printfn "    python -c \"import pandas as pd; import matplotlib.pyplot as plt; \\"
printfn "      df = pd.read_csv('book/code/h2_dissociation.csv'); \\"
printfn "      plt.plot(df.R_angstrom, df.E_total_Ha, 'o-'); \\"
printfn "      plt.xlabel('Bond length (Å)'); plt.ylabel('Energy (Ha)'); \\"
printfn "      plt.title('H₂ Dissociation Curve (STO-3G, JW)'); \\"
printfn "      plt.savefig('book/code/h2_dissociation.png', dpi=150); \\"
printfn "      plt.show()\""
