// ══════════════════════════════════════════════════════════════
// Chapter 18 Companion: Verified Hamiltonian to Circuit + Cost Scan
// ══════════════════════════════════════════════════════════════
// Run with: dotnet fsi code/ch18-pipeline.fsx
// Prereq:   dotnet build --configuration Release
//
// This script demonstrates the validated untapered path from Chapter 18:
//   1. Build Hamiltonian → 2. Trotterize → 3. Export
//
// It then applies the skeleton API across the H₂ bond-length grid
// to report Hamiltonian and circuit costs. Reference HF/FCI energies
// are generated independently by ch18-dissociation-scan.py.
//
// Output: _build/data/h2_circuit_costs.csv

#r "nuget: FockMap, 0.9.0"
#load "ch03-spin-orbitals.fsx"

open System
open System.IO
open System.Numerics
open Encodings
open Encodings.BravyiKitaev
open Encodings.CircuitOutput
open Encodings.Hamiltonian
open Encodings.JordanWigner
open Encodings.MajoranaEncoding
open Encodings.TreeEncoding
open Encodings.Trotterization

// ══════════════════════════════════════════════════════════════
//  Part 1: Verified Hamiltonian to Circuit (single geometry)
// ══════════════════════════════════════════════════════════════

printfn ""
printfn "Chapter 18: Verified Hamiltonian to Circuit"
printfn "============================================"
printfn ""

let encoders = [
    ("Jordan-Wigner",  jordanWignerTerms)
    ("Bravyi-Kitaev",  bravyiKitaevTerms)
    ("Parity",         parityTerms)
    ("Binary Tree",    balancedBinaryTreeTerms)
    ("Ternary Tree",   ternaryTreeTerms)
    ("Vlasov Tree",    vlasovTreeTerms)
]

let pruneZeroTerms (hamiltonian: PauliRegisterSequence) =
    hamiltonian.DistributeCoefficient.SummandTerms
    |> Array.filter (fun term -> Complex.Abs term.Coefficient > 1e-12)
    |> PauliRegisterSequence

let canonicalJw =
    computeHamiltonian
        ``Ch03-spin-orbitals``.h2RawPhysicistFactory
        4u
    |> pruneZeroTerms
let canonicalJwTerms =
    canonicalJw.DistributeCoefficient.SummandTerms
    |> Array.filter (fun term -> Complex.Abs term.Coefficient > 1e-12)

let requireCanonicalCoefficient signature expected =
    let actual =
        canonicalJwTerms
        |> Array.tryFind (fun term -> term.Signature = signature)
        |> Option.map (fun term -> term.Coefficient.Real)
        |> Option.defaultWith (fun () -> failwithf "Missing Pauli term %s" signature)

    if abs (actual - expected) > 1e-9 then
        failwithf
            "FockMap Hamiltonian convention mismatch for %s: expected %.10f, got %.10f. Refusing to emit circuit-cost output."
            signature
            expected
            actual

if canonicalJwTerms.Length <> 15 then
    failwithf "Expected 15 nonzero JW terms, got %d" canonicalJwTerms.Length

requireCanonicalCoefficient "IIII" -0.8121706072
requireCanonicalCoefficient "XXYY" -0.0453026155

printfn "  %-15s  %6s  %5s  %10s  %11s"
    "Encoding" "Qubits" "Terms" "CNOTs/step" "Total gates"
printfn "  %-15s  %6s  %5s  %10s  %11s"
    "───────────────" "──────" "─────" "──────────" "───────────"

for (name, encoder) in encoders do
    let ham =
        computeHamiltonianWith
            encoder
            ``Ch03-spin-orbitals``.h2RawPhysicistFactory
            4u
        |> pruneZeroTerms
    let step = firstOrderTrotter 0.1 ham
    let stats = trotterStepStats step
    let nonzeroTerms =
        ham.DistributeCoefficient.SummandTerms
        |> Array.filter (fun term -> Complex.Abs term.Coefficient > 1e-12)

    printfn "  %-15s  %6d  %5d  %10d  %11d"
        name
        4
        nonzeroTerms.Length
        stats.CnotCount
        stats.TotalGates

// Show the QASM for JW
printfn ""
printfn "OpenQASM 3.0 output (Jordan-Wigner, untapered):"
printfn "────────────────────────────────────────────────"
let jwHam =
    computeHamiltonian
        ``Ch03-spin-orbitals``.h2RawPhysicistFactory
        4u
    |> pruneZeroTerms
let jwStep = firstOrderTrotter 0.1 jwHam
let jwGates = decomposeTrotterStep jwStep
let qasm = toOpenQasm defaultOpenQasmOptions 4 jwGates
printfn "%s" qasm

// ══════════════════════════════════════════════════════════════
//  Part 2: H₂ Hamiltonian and Circuit Costs Across Geometries
// ══════════════════════════════════════════════════════════════

printfn ""
printfn "H₂ Circuit-Cost Scan"
printfn "===================="
printfn ""

// ── Load integrals from JSON (generated by ch18-generate-h2-integrals.py) ──

// Simple JSON parser for our specific format (avoids external dependencies)
let loadIntegralsFromJson (jsonPath : string) : (float * float * Map<string, Complex>) list =
    // We parse the JSON manually since we don't want to add a NuGet dependency
    // for a companion script. The format is known and simple.
    let text = File.ReadAllText(jsonPath)

    // Extract each bond-length entry
    let mutable results = []

    // Split by top-level keys (bond lengths like "0.40", "0.50", ...)
    let bondLengthPattern = System.Text.RegularExpressions.Regex("\"(\\d+\\.\\d+)\"\\s*:\\s*\\{")
    let matches = bondLengthPattern.Matches(text)

    for m in matches do
        let bondLength = float m.Groups.[1].Value

        // Find the section for this bond length
        let startIdx = m.Index
        let mutable depth = 0
        let mutable endIdx = startIdx
        let mutable foundStart = false
        for i in startIdx .. text.Length - 1 do
            if text.[i] = '{' then
                depth <- depth + 1
                foundStart <- true
            elif text.[i] = '}' then
                depth <- depth - 1
                if foundStart && depth = 0 && endIdx = startIdx then
                    endIdx <- i
        let section = text.[startIdx .. endIdx]

        // Extract Vnn
        let vnnMatch = System.Text.RegularExpressions.Regex("\"Vnn\"\\s*:\\s*([\\d.eE+-]+)").Match(section)
        let vnn = if vnnMatch.Success then float vnnMatch.Groups.[1].Value else 0.0

        // Extract integrals
        let integralsMatch = System.Text.RegularExpressions.Regex("\"integrals\"\\s*:\\s*\\{([^}]+)\\}").Match(section)
        if integralsMatch.Success then
            let intSection = integralsMatch.Groups.[1].Value
            let kvPattern = System.Text.RegularExpressions.Regex("\"([0-9,]+)\"\\s*:\\s*([\\d.eE+-]+)")
            let kvMatches = kvPattern.Matches(intSection)
            let mutable integralMap = Map.empty
            for kv in kvMatches do
                let key = kv.Groups.[1].Value
                let value = float kv.Groups.[2].Value
                integralMap <- integralMap |> Map.add key (Complex(value, 0.0))
            results <- (bondLength, vnn, integralMap) :: results

    results |> List.sortBy (fun (r, _, _) -> r)

// Try to load from JSON file
let scriptDir = __SOURCE_DIRECTORY__
let jsonPath = Path.Combine(scriptDir, "h2_dissociation_integrals.json")

let dissociationData =
    if File.Exists(jsonPath) then
        printfn "  Loading integrals from %s" (Path.GetFileName(jsonPath))
        loadIntegralsFromJson jsonPath
    else
        printfn "  JSON file not found. Run ch18-generate-h2-integrals.py first."
        printfn "  Using equilibrium geometry only (R = 0.74 Å)."
        [ (0.74, 0.7151043391, ``Ch03-spin-orbitals``.h2RawPhysicistIntegrals) ]

// ── Precompute the skeleton once ──
let skeleton = computeHamiltonianSkeleton jordanWignerTerms 4u
printfn "  Skeleton precomputed (structure encoded once)."
printfn ""

// ── Scan ──
printfn "  %8s  %12s  %12s  %12s"
    "R (Å)" "Terms" "CNOTs/step" "Total gates"
printfn "  %8s  %12s  %12s  %12s"
    "────────" "────────────" "────────────" "────────────"

// Collect data for CSV output
let mutable csvLines = [ "R_angstrom,terms,cnots_per_step,total_gates" ]

for (bondLength, _vnn, integralMap) in dissociationData do
    let rawFactory key = integralMap |> Map.tryFind key
    let ham = applyCoefficients skeleton rawFactory |> pruneZeroTerms
    let step = firstOrderTrotter 0.1 ham
    let stats = trotterStepStats step

    // This script constructs Hamiltonians and circuits. It does not infer
    // a ground-state energy from the identity coefficient.
    let terms =
        ham.DistributeCoefficient.SummandTerms
        |> Array.filter (fun term -> Complex.Abs term.Coefficient > 1e-12)
    let nTerms = terms.Length

    printfn "  %8.2f  %12d  %12d  %12d"
        bondLength nTerms stats.CnotCount stats.TotalGates

    csvLines <- csvLines @ [
        sprintf "%.2f,%d,%d,%d"
            bondLength nTerms stats.CnotCount stats.TotalGates
    ]

// ── Write derived output outside canonical source data ──
let repositoryRoot = Directory.GetParent(scriptDir).FullName
let buildDataDir = Path.Combine(repositoryRoot, "_build", "data")
Directory.CreateDirectory(buildDataDir) |> ignore
let csvPath = Path.Combine(buildDataDir, "h2_circuit_costs.csv")
File.WriteAllLines(csvPath, csvLines)

printfn ""
printfn "  Data written to: %s" (Path.GetFileName(csvPath))
printfn "  Reference energies: h2_dissociation.csv (generated by PySCF)"
