title: "From Molecules to Quantum Circuits"
description: "A Computational Guide to Fermion-to-Qubit Encodings"
url: https://johnazariah.github.io
baseurl: /encodings-book
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
plugins:
  - jekyll-optional-front-matter
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
exclude:
  - Makefile
  - "*.fsx"
  - "*.py"
  - "*.csv"
  - "*.json"
